import { Metadata } from "next";
import "@/styles/globals.css";
import { Source_Sans_3 as FontSans } from "next/font/google";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "SMARTLION",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antikaliased flex flex-col",
          fontSans.variable
        )}
      >
        <Navbar />
        <main className="grow bg-slate-50/50 mt-[var(--navbar-height)]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
